---
title: "Random Forest Feature Ranking"
output: html_document
---

```{r}
library(caret)
library(rpart)
library(e1071)
library(randomForest)
library(PRROC)
library(MLmetrics)
library(ggplot2)
```


```{r}
df = read.csv(url("https://archive.ics.uci.edu/ml/machine-learning-databases/00519/heart_failure_clinical_records_dataset.csv"))
```

```{r}
df = subset(df, select = -c(time))
df$DEATH_EVENT = as.factor(df$DEATH_EVENT)
df
```

```{r}
results_df <- data.frame(age=numeric(0), anaemia=numeric(0), creatinine_phosphokinase=numeric(0), diabetes=numeric(0), ejection_fraction=numeric(0), high_blood_pressure=numeric(0), platelets=numeric(0), serum_creatinine=numeric(0), serum_sodium=numeric(0), sex=numeric(0), smoking=numeric(0) )
colnames(results_df) = c("age", "anaemia", "creatinine_phosphokinase", "diabetes", "ejection_fraction", "high_blood_pressure", "platelets", "serum_creatinine", "serum_sodium", "sex", "smoking")
#results_df = t(results_df)
print(results_df)

n = 100

for(i in 1:n) {
  
  df = df[sample(nrow(df)),]
  
  model = randomForest(DEATH_EVENT ~ ., data = df, importance=TRUE, proximity = TRUE)
  
  #im = model$importance
  imp = as.data.frame(model$importance)
  #im = t(im)
  #print(imp)
  #imp = varImp(model)
  
  #print(imp)
  #varImpPlot(model)
  
  imp$clinical_feature = row.names(imp)
  #imp$clinical_feature
  
  imp$"MDA" = imp$"MeanDecreaseAccuracy"
  imp$"Gini" = imp$"MeanDecreaseGini"
  
  rank = imp[order(imp$"clinical_feature"),]
  #print(rank)
  
  if (i == 1){
    results_df = rank
  } else {
    results_df$"MDA" = results_df$"MDA" + rank$"MeanDecreaseAccuracy"
    results_df$"Gini" = results_df$"Gini" + rank$"MeanDecreaseGini"
    
 
  }
  
}
print(results_df)
results_df$"finalMDA" = results_df$"MDA" / n
results_df$"finalGini" = results_df$"Gini" / n
results_df = results_df[order(-results_df$"finalMDA"),]
results_df = results_df[order(-results_df$"finalGini"),]

results_df$"finalPos" = c(1:dim(results_df)[1])

print(results_df)
#impoo = imp
```

```{r}
write.csv(final_result, "rf_feature_ranking_results.csv")
```

```{r}
write.csv(results_df, "rf_feature_ranking_results.csv")
```

```{r}
library(forcats)

results_df %>%
mutate(clinical_feature = fct_reorder(as.factor(clinical_feature), finalGini)) %>%
ggplot( aes(x=finalGini, y=clinical_feature)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) + xlab("Gini Impurity") + ylab("") 
ggsave(filename="gini_importance.png", plot=last_plot(), device = "png")
```

```{r}
library(forcats)
results_df %>%
mutate(clinical_feature = fct_reorder(as.factor(clinical_feature), finalMDA)) %>%
ggplot( aes(x=finalMDA, y=clinical_feature)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) + xlab("Accuracy Reduction") + ylab("")
ggsave(filename="mda_importance.png", plot=last_plot(), device = "png")
```

```{r}

rank <- randomForest(DEATH_EVENT ~ ., data = train_data, importance=TRUE)
varImp(rank)
#varImpPlot(rank)
```
```{r}
p <- ggplot(df, aes(x=serum_creatinine, y=ejection_fraction, color=factor(df$DEATH_EVENT, labels = c("survived", "dead")) )) + geom_point(size = 3)  + xlab("serum creatinine")   + ylab("ejection fraction") +  labs(colour="patient status", size="") + theme(text = element_text(size=30))
plot(p)
```


```{r}
p = ggplot(data = df, aes(x=serum_creatinine, y = ejection_fraction, colour = sample)) + geom_point(size = 3) + xlab("serum creatinine")   + ylab("ejection fraction") + scale_fill_manual(values=c(palette_ro[2], palette_ro[7]))
plot(p)
```

```{r}
library(car)
scatterplot(ejection_fraction ~ serum_creatinine | DEATH_EVENT, data = df, xlab = "serum creatinine", ylab = "ejection fraction")
#abline(lm(ejection_fraction ~ serum_creatinine))
```

```{r}
library(mlr)
palette()
da = makeClassifTask(data=df, target = "DEATH_EVENT")
rf = makeLearner("classif.randomForest", predict.type = "response")
plotLearnerPrediction(rf, da, features = c("serum_creatinine", "ejection_fraction")) 
  #scale_fill_manual(values=c(palette[2], palette[7])) +
  #theme_minimal(base_size = 12)
```


