---
title: "Decision Tree Classifier"
output: html_document
---

```{r}
library(caret)
library(rpart)
library(e1071)
library(randomForest)
library(PRROC)
library(MLmetrics)
library(mltools)
library(pastecs)
```

```{r}
df = read.csv(url("https://archive.ics.uci.edu/ml/machine-learning-databases/00519/heart_failure_clinical_records_dataset.csv"))

dff = subset(df, select = -c(time))
dff$DEATH_EVENT = as.factor(dff$DEATH_EVENT)
```



```{r}

results_df <- data.frame(mcc=numeric(0), f1=numeric(0), accuracy=numeric(0), tp_rate=numeric(0), tn_rate=numeric(0), prc_auc=numeric(0), roc_auc=numeric(0))
colnames(results_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")

n = 100

for(i in 1:n) {
  
  split <- createDataPartition(dff$DEATH_EVENT, p = 0.8, list = FALSE)
  train_data <- dff[split, ]
  test_data <- dff[-split, ]
    # train the decision tree classifier on the training data
  model <- rpart(DEATH_EVENT ~ ., data = train_data, method="class")

  # evaluate the model on the test data
  predictions <- predict(model, test_data, type="class")
  
  rate = rates1(predictions, test_data$DEATH_EVENT)
  
  my_df = data.frame(rate)
  colnames(my_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")
  
  
  results_df = rbind(results_df, my_df)
}
print(results_df)
stat = stat.desc(results_df)
final_result = (stat)[c("median", "mean"),]
final_result
```

```{r}
write.csv(final_result, "dec_tree_all_features_results.csv")
```

```{r}
write.csv(results_df, "dec_tree_all_features_results_log.csv")
```

