---
title: "XGBOOST Classification with top two features"
output: html_document
---

```{r}
library(caret)
library(rpart)
library(e1071)
library(randomForest)
library(PRROC)
library(MLmetrics)
library(xgboost)
```

```{r}
df = read.csv(url("https://archive.ics.uci.edu/ml/machine-learning-databases/00519/heart_failure_clinical_records_dataset.csv"))
df = subset(df, select = c(ejection_fraction, serum_creatinine, DEATH_EVENT))
```

```{r}
split <- createDataPartition(df$DEATH_EVENT, p = 0.8, list = FALSE)
  train_data <- df[split, ]
  test_data <- df[-split, ]
```
  
```{r}  
dtrain <- xgb.DMatrix(data = as.matrix(select(train_data, -DEATH_EVENT)), label = train_data$DEATH_EVENT)
  
model = xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
  
  pred <- as.factor(predict(model, as.matrix(select(test_data, -DEATH_EVENT))) >= 0.5) %>%
  fct_recode("0" = "FALSE", "1" = "TRUE")
#confusionMatrix(pred, as.factor(test_data$DEATH_EVENT), positive = "1")
confusionMatrix(pred, as.factor(test_data$DEATH_EVENT))

```



```{r}

results_df <- data.frame(mcc=numeric(0), f1=numeric(0), accuracy=numeric(0), tp_rate=numeric(0), tn_rate=numeric(0), prc_auc=numeric(0), roc_auc=numeric(0))
colnames(results_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")

n = 100

for(i in 1:n) {
  
  split <- createDataPartition(df$DEATH_EVENT, p = 0.8, list = FALSE)
  train_data <- df[split, ]
  test_data <- df[-split, ]
  
  
  dtrain <- xgb.DMatrix(data = as.matrix(select(train_data, -DEATH_EVENT)), label = train_data$DEATH_EVENT) #Virkar
  
  model = xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
  
  
  pred <- as.factor(predict(model, as.matrix(select(test_data, -DEATH_EVENT))) >= 0.5) %>%
  fct_recode("0" = "FALSE", "1" = "TRUE")
#confusionMatrix(pred, as.factor(test_data$DEATH_EVENT), positive = "1")
confusionMatrix(pred, as.factor(test_data$DEATH_EVENT))

  
  rate = rates1(pred, as.factor(test_data$DEATH_EVENT))
  
  
  my_df = data.frame(rate)
  colnames(my_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")
  #colnames(results_df) = colnames(my_df)
  
  results_df = rbind(results_df, my_df)
}
print(results_df)
stat = stat.desc(results_df)
final_result = (stat)[c("median", "mean"),]
final_result

```

```{r}
write.csv(final_result, "xgboost_classifier_top_features_results_correct.csv")
```

```{r}
write.csv(results_df, "xgboost_classifier_top_features_results_log_correct.csv")
```







